

?> 说下你遇到的异常？

## 1. 异常分类

### 1.1. 受检查异常

程序必须处理，否则编译不通过。

### 1.2. 非检查异常

> 派生于 Error 类或 RuntimeException 类的所有异常成为非检查异常（unchecked）。

#### 1.2.1. 运行时异常（RuntimeException）

运行时异常都是 RuntimeException 类及其子类，如 NullPointerException、IndexOutOfBoundsException。

运行时异常的特点：
*  非检查异常：编译器不会检查这些异常，程序中可以选择捕获处理，也可以不处理，程序不处理也会编译通过。
* 一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生。


## 2. 常见的异常

[Java 中的常见异常](https://www.processon.com/view/link/5ecf8b12f346fb6907231a8b)

### 2.1. java.lang.NullPointerException

**变量未初始化，被调用方法的对象为 null**

```java
String s = null;
System.out.println(s.length());
```

**变量未初始化，访问 null 对象属性**

```java
String[] s = null;
System.out.println(s.length);
```

**数组元素未初始化**

数组的初始化是对数组分配需要的空间，而初始化后的数组，其中的元素并没有实例化，在调用时出现异常。

```java
String[] s = new String[5];
System.out.println(s[0].length());
```

**方法传入的参数为 null**

```java
@Test(description = "空指针异常测试：方法传入参数为 null")
public void testNullPointerException3(){
    nullPointerException3(null);
}

private void nullPointerException3(Object o){
    System.out.println(o.hashCode());
}
```

**方法返回值为 null**

```java
HashMap<String, String> map = new HashMap();
map.put("a",null);
System.out.println(map.get("a").length());
```

参考资料：

1. [Java避免NullPointerException的一些技巧](https://blog.csdn.net/u014691866/article/details/82689403)

### 2.2. java.lang.ClassNotFoundException

调用 Class.forName()

```java
Class.forName("a.b.c.ClassA");
```

ClassLoader 中的 loadClass()

```java
this.getClass().getClassLoader().loadClass("a.b.c.ClassA");
```

ClassLoader 中的 findSystemClass()

> 自定义 ClassLoader 重写 findClass() 方法，这时可以调用 findSystemClass() 方法。

```java
protected final Class<?> findSystemClass(String name)
    throws ClassNotFoundException
{
    ClassLoader system = getSystemClassLoader();
    if (system == null) {
        if (!checkName(name))
            throw new ClassNotFoundException(name);
        Class<?> cls = findBootstrapClass(name);
        if (cls == null) {
            throw new ClassNotFoundException(name);
        }
        return cls;
    }
    return system.loadClass(name);
}
```

### 2.3. java.lang.ClassCastException

```java
@Test(description = "java.lang.ClassCastException: java.lang.Object cannot be cast to entity.Person")
public void testClassCastException() {
  Person person = (Person) new Object();
}
```

### 2.4. java.lang.CloneNotSupportedException

当类没有实现 Cloneable 接口或者不支持克隆方法（这种情况是什么？）时，调用 super.clone() 方法则抛出该异常。

```java
  @Test(description = "没有实现 Cloneable 接口：java.lang.CloneNotSupportedException: exception.sample.CloneNotSupportedExceptionTest")
  public void testCloneNotSupportedException() throws CloneNotSupportedException {
      super.clone();
  }
```

### 2.5. java.lang.ArrayIndexOutOfBoundsException

```java
String[] s = {"a", "b", "c"};
System.out.println(s[3]);
```

### 2.6. java.lang.ArrayStoreException

```java
  @Test(description = "java.lang.ArrayStoreException: java.lang.String")
  public void testArrayStoreException() {
    Object[] data = new Integer[3];
    data[0] = "abc";
  }
```

### 2.7. java.lang.FileNotFoundException

```java
  @Test(description = "java.io.FileNotFoundException: z:\\a.txt (系统找不到指定的路径。)")
  public void testFileNotFoundException() throws FileNotFoundException {
    File file = new File("z:/a.txt");
    BufferedReader reader = new BufferedReader(new FileReader(file));
    try {
      reader.close();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
```

### 2.8. java.io.IOException

见 [java.lang.FileNotFoundException](#java.lang.FileNotFoundException)

### 2.9. java.lang.NumberFormatException

```java
int a = Integer.valueOf("12-3");
```

### 2.10. java.lang.IllegalArgumentException

```java
@Test(description = "java.lang.IllegalArgumentException: Cannot format given Object as a Date")
public void testIllegalArgumentException() {
  SimpleDateFormat dateFormat= new SimpleDateFormat("yyyy-MM");
  String format = dateFormat.format("2020-05");
  System.out.println(format);
}
```

### 2.11. java.lang.ArithmeticException

```java
@Test(description = "java.lang.ArithmeticException: / by zero")
public void testArithmeticException() {
	System.out.println(5/0);
}
```

### 2.12. java.lang.InstantiationException

1. 通过反射实例化注解、接口、抽象类等，导致实例化异常
2. 类中没有无参构造器

```java
  @Test(description = "注解无法实例化 java.lang.InstantiationException: org.testng.annotations.Test")
  public void testInstantiationException() throws IllegalAccessException, InstantiationException {
    Test calendar = Test.class.newInstance();
  }
```

### 2.13. java.lang.NoSuchFieldException

见 [java.lang.IllegalAccessException](#java.lang.IllegalAccessException)

### 2.14. java.lang.NoSuchMethodException

略

### 2.15. java.lang.IllegalAccessException

```java
public class IllegalAccessExceptionTest {

  @Test
  public void testIllegalAccessException() throws ClassNotFoundException, IllegalAccessException, NoSuchFieldException {
    Class clazz = Class.forName("exception.sample.AccessDemo");
    Field field = clazz.getDeclaredField("name");
    //fields[0].setAccessible(true);  //设置可访问
    field.set(new AccessDemo(), "ss");
  }
  
}

class AccessDemo{

  private String name;

}
```

### 2.16. java.sql.SQLException

```java
//获取数据库连接
Connection conn = null;
try {
    conn = DriverManager.getConnection(
        "jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC",
        "root",
        "****");
} catch (SQLException throwables) {
    throwables.printStackTrace();
}finally {
    if (conn != null){
    try {
        conn.close();
    } catch (SQLException throwables) {
        throwables.printStackTrace();
    }
    }
}
```

### 2.17. java.lang.OutOfMemoryError

```java
  //设置 JVM 参数：-Xms2m -Xmx2m
  @Test(description = "Exception in thread \"main\" java.lang.OutOfMemoryError: Java heap space")
  public void testOutOfMemoryError() {
    List<String> list = new ArrayList<>();
    while (true){
      list.add(UUID.randomUUID().toString());
    }
  }
```

### 2.18. java.lang.AssertionError

```java
  @Test(description = "java.lang.AssertionError: 计算 1 + 1，预期值：3，实际值 2 ")
  public void testAssertionError() {
    assert 1 + 1 == 3 : "计算 1 + 1，预期值：3，实际值 2 ";
  }
```

## 3. try-with-resources

### 3.1. 语法

try-with-resources 语法：

```java
try(Resources res = ...){
  // work with res，记为工作区
}
```

1. try() 中的资源类需要实现 {@link AutoCloseable} 接口，编译时生成调用 close() 方法的代码
2. try() 中的变量隐式声明为 final，因为如果在 try 块中修改变量引用，将导致之前引用的资源无法关闭
3. try() 中可以有多个资源，多个资源用 ; 隔开

try-with-resources 使用：

1. 限制1：资源类必须实现 AutoCloseable 接口
1. 限制2：资源不能重新赋值
3. 建议1：如果有三个以上资源，编译后的 try 嵌套较深，不建议使用该语法

try-with-resources 异常：

1. 将第一个抛出的异常作为最终异常（可能是工作区异常，也可能是 close() 抛出的异常）
2. 在外层的 catch 块中，将 close() 抛出的异常（如果有）作为被抑制异常加入最终异常的被抑制异常列表。

### 3.2. 编译规则

1. 将 try() 中的资源声明和初始化代码，编译进 try 块中。
2. 如果有多个资源，编译后结构，按照资源声明顺序嵌套。

### 3.3. 编译前结构

```java
try(资源 R1; 资源 R2; ...; 资源 RN){
  //try 代码块，记为工作区 B
}
```

### 3.4. 编译后结构

> 这里讨论的编译后结构是指编译后外层 Try 块中的代码结构。

当只有一个资源时：

```java
Resources resources = new Resources();    //try() 中的第一个资源
Throwable copy = null;                    //声明一个异常变量，用于追加被抑制异常到真实异常

try {
  // try 块内容，记为 R1_Try。当只有一个资源时，R1_Try = B。
} catch (Throwable e) {                   //try 块抛出的异常，这里我们暂时称呼它为真实异常
  copy = e;                               //将真实异常对象的引用赋值给 copy
  throw e;                                //抛出真实异常，注意到这里只是为了提高真实异常作用域的范围
} finally {
  if (resources != null) {                //如果资源不为 null
    if (copy != null) {                   //如果发生了真实异常
      try {
        resources.close();                //关闭资源
      } catch (Throwable e) {             //关闭资源是抛出异常
        copy.addSuppressed(e);            //因为已经有真实异常，将资源关闭异常作为被抑制异常处理
      }
    } else {                              //如果没发生真实异常，直接调用 close() 关闭资源
      resources.close();                  //如果 close() 抛出异常，将作为上一层的真实异常处理
    }
  }
}
```

当有两个资源时：

1. 第二个资源的编译后结构，和只有一个资源时的编译后结构相同，其中 R2_Try = B。
2. 第一个资源的编译后结构，和只有一个资源时的编译后结构相同，其中 R1_Try = 第二个资源的编译后内容。

当有多个资源时：

1. 倒数第一个资源 RN 的编译后结构，和只有一个资源时的编译后结构相同，其中 RN_Try = B。
2. 倒数第 N-1 个资源 RN-1 的编译后结构，和只有一个资源时的编译后结构相同，其中 RN-1_Try = RN_Try。
3. 多个资源，以此类推，重复第 2 步。



